name: CI Build

on:
  pull_request:
  push:
    branches:
      - main
      - '**.*.*'
  workflow_dispatch:
    inputs:
      vendor:
        description: 'Choose loader or all'
        required: true
        default: 'fabric'
        type: choice
        options:
          - all
          - fabric
          - forge
          - neoforge
          - quilt

jobs:
  build-fabric:
    if: "contains(github.event.inputs.vendor, 'fabric') || github.event.inputs.vendor == 'all'"
    uses: ./.github/workflows/_build-loader.yml
    with:
      loader: fabric
      mc_version: ${{ github.ref_name }}
      mod_version: ${{ github.sha }}

  build-forge:
    if: "contains(github.event.inputs.vendor, 'forge') || github.event.inputs.vendor == 'all'"
    uses: ./.github/workflows/_build-loader.yml
    with:
      loader: forge
      mc_version: ${{ github.ref_name }}
      mod_version: ${{ github.sha }}

  build-neoforge:
    if: "contains(github.event.inputs.vendor, 'neoforge') || github.event.inputs.vendor == 'all'"
    uses: ./.github/workflows/_build-loader.yml
    with:
      loader: neoforge
      mc_version: ${{ github.ref_name }}
      mod_version: ${{ github.sha }}

  build-quilt:
    if: "contains(github.event.inputs.vendor, 'quilt') || github.event.inputs.vendor == 'all'"
    uses: ./.github/workflows/_build-loader.yml
    with:
      loader: quilt
      mc_version: ${{ github.ref_name }}
      mod_version: ${{ github.sha }}
