name: Metadata

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      provider:
        description: 'Choose provider or all'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - modrinth
          - curseforge
          - github

jobs:
  metadata-modrinth:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.provider == 'modrinth' || inputs.provider == 'all' }}
    uses: ./.github/workflows/_metadata-provider.yml
    with:
      provider: modrinth
      modrinth_project_slug: dispenser-breeding
    secrets: inherit

  metadata-curseforge:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.provider == 'curseforge' || inputs.provider == 'all' }}
    uses: ./.github/workflows/_metadata-provider.yml
    with:
      provider: curseforge
    secrets: inherit

  metadata-github:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.provider == 'github' || inputs.provider == 'all' }}
    uses: ./.github/workflows/_metadata-provider.yml
    with:
      provider: github
    secrets: inherit
