name: Publish to Modrinth

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew build

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: zlKk8V6R
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            build/libs/dispenserbreeding-*.jar

          name: "[Fabric] ${{ github.event.release.target_commitish }}-${{ github.event.release.tag_name }}"
          version: "${{ github.event.release.target_commitish }}-${{ github.event.release.tag_name }}-fabric"

          loaders: fabric
          game-versions: 26.1

          dependencies: |
            fabric-api(required)